# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e35b0d6233fd57af4f8aaf1fe921c8a539bf022c22280a690e7fabc02ebb7523bf0f0117dd16c4f78df4e80f4291a0a088bc101322d5397ae16701aa9d262e4e

test:
  secret_key_base: cd29f048e0f82eae85681197a7dfb44df2522317211d49ab6edf3c7b448f3ad577a1ba27b43ed8fb15a0e5b70f7ae55532c0970576260e59770deaa86a31f98a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
